/**
* This file and any referenced files were automatically generated by @cosmology/telescope@latest
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or npm scripts command that is used to regenerate this bundle.
*/


import { HttpEndpoint } from "@interchainjs/types";
import { BinaryReader, BinaryWriter } from "./binary";
import { getRpcClient } from "./extern";
import { isRpc, Rpc } from "./helpers";
import { TelescopeGeneratedCodec, DeliverTxResponse, Message, StdFee } from "./types";
import { toConverters, toEncoders } from "@interchainjs/cosmos/utils";

export interface QueryBuilderOptions<TReq, TRes> {
  encode: (request: TReq, writer?: BinaryWriter) => BinaryWriter
  decode: (input: BinaryReader | Uint8Array, length?: number) => TRes
  service: string,
  method: string,
}

export function buildQuery<TReq, TRes>(opts: QueryBuilderOptions<TReq, TRes>) {
    return async (client: EndpointOrRpc, request: TReq) => {
      let rpc: Rpc | undefined;

      if(isRpc(client)) {
        rpc = client;
      } else {
        rpc = client ? await getRpcClient(client) : undefined;
      }

      if (!rpc) throw new Error("Query Rpc is not initialized");

      const data = opts.encode(request).finish();
      const response = await rpc.request(opts.service, opts.method, data);
      return opts.decode(response);
    };
}

export interface ITxArgs<TMsg> {
  signerAddress: string;
  message: TMsg | TMsg[];
  fee: StdFee | 'auto';
  memo: string;
}

export function isISigningClient(client: unknown): client is ISigningClient {
  return client !== null && client !== undefined
    && typeof (client as ISigningClient).signAndBroadcast === 'function'
    && typeof (client as ISigningClient).addConverters === 'function'
    && typeof (client as ISigningClient).addEncoders === 'function';
}

export interface ISigningClient {
  /**
   * register converters
   */
  addConverters: (converters: AminoConverter[]) => void;
  /**
   * register encoders
   */
  addEncoders: (encoders: Encoder[]) => void;

  signAndBroadcast: (
    signerAddress: string,
    message: Message<any>[],
    fee: StdFee | "auto",
    memo: string
  ) => Promise<DeliverTxResponse>;
}

export interface TxBuilderOptions {
  msg: TelescopeGeneratedCodec<any, any, any>
}

export function buildTx<TMsg>(opts: TxBuilderOptions) {
  return async (
    client: ISigningClient,
    signerAddress: string,
    message: TMsg | TMsg[],
    fee: StdFee | 'auto',
    memo: string
  ): Promise<DeliverTxResponse> => {
    if (!client) throw new Error("SigningClient is not initialized");

    //register all related encoders and converters
    client.addEncoders(toEncoders(opts.msg));
    client.addConverters(toConverters(opts.msg));

    const data = Array.isArray(message)
      ? message.map(msg => ({
          typeUrl: opts.msg.typeUrl,
          value: msg,
        }))
      : [{
          typeUrl: opts.msg.typeUrl,
          value: message,
        }];
    return client.signAndBroadcast!(signerAddress, data, fee, memo);
  };
}

export interface Encoder {
  typeUrl: string;
  fromPartial: (data: any) => any;
  encode: (data: any) => Uint8Array;
}

export interface AminoConverter {
  typeUrl: string;
  aminoType: string;
  fromAmino: (data: any) => any;
  toAmino: (data: any) => any;
}

export type EndpointOrRpc = string | HttpEndpoint | Rpc ;
